teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - christinaharter
      - daniela-barbosa
      - davidwboswell
      - hartm
      - jwagantall
      - minyu66
      - thelinuxfoundation
  - name: tac
    maintainers:
      - tkuhrt
    members:
      - EnriqueL8
      - VRamakrishna
      - arsulegai
      - dmueller2001
      - hendrikebbers
      - matthew1001
      - mbrandenburger
      - petermetz
      - wenjing
repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
  - name: mentorship-program
    teams:
      lf-staff: maintain
      tac: maintain
    visibility: public
